services:
  proxy:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - app
  app:
    build:
      context: ./web/src
      args:
        - NEW_RELIC_AGENT_VERSION=11.3.0.16
        - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
        - NEW_RELIC_APP_NAME=app
    volumes:
      # - ./web/config/php.ini:/usr/local/etc/php/php.ini
      - ./web/src:/var/www
    ports:
      - 80:80
  newrelic-php-daemon:
    image: newrelic/php-daemon

  # db:
  #   image: postgres:17
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ./postgres/init/:/docker-entrypoint-initdb.d
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
